### ISSUE TITLE
Mobile Issue: Cannot Save Chat

### ISSUE THREAD

**Issue by apislogic** [logancyang/obsidian-copilot#884]
- [x ] Disable all other plugins besides Copilot **(required)**
- [x ] Screenshot of note + Copilot chat pane + dev console added **(required)**
![image](https://github.com/user-attachments/assets/091c13b2-d836-44e4-b28e-b534134cb623)

Copilot version: 2.7.4

**Describe how to reproduce**
In Obsidian Mobile (v 1.7.7) chats do not save if the designated "Default Conversation Folder Name" already exists. The save fails with the error: 
> plugin:copilot:159469 Error saving chat as note: Error: Folder already exists.
>     at t.<anonymous> (app.js:1:750805)
>     at app.js:1:237226
>     at Object.next (app.js:1:237331)
>     at a (app.js:1:236049)
 
If the folder designated as ""Default Conversation Folder Name" does not already exist, the save works as expected. However, subsequent updates/new chat saves then do now work after.

**Expected behavior**

Expected behavior is for copilot chats to save/update on demand or on new chat creation.

**Screenshots**
See this Loom for a demo: https://www.loom.com/share/ea356400ce8441a782b964c9acd6cd32?sid=4fbbf8f0-17b1-46ed-bd51-68b034b3ca11

**Comment by logancyang** [comment]
Probably because the util from Obsidian API that checks for folder existence did not work on mobile (android in this case?)

**Comment by jrossi** [comment]
I am getting the error on the desktop.  

<img width="1002" alt="Screenshot 2024-12-02 at 4 59 26 AM" src="https://github.com/user-attachments/assets/636c3011-0430-4de9-b2d6-ee262e33ced1">

**Comment by logancyang** [comment]
> I am getting the error on the desktop.
> 
> <img alt="Screenshot 2024-12-02 at 4 59 26 AM" width="1002" src="https://private-user-images.githubusercontent.com/58556/391496066-636c3011-0430-4de9-b2d6-ee262e33ced1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxMzQ0NDksIm5iZiI6MTczMzEzNDE0OSwicGF0aCI6Ii81ODU1Ni8zOTE0OTYwNjYtNjM2YzMwMTEtMDQzMC00ZGU5LWIyZDYtZWUyNjJlMzNjZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDEwMDkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5Yjk3ZjVkZDgzNDI0YTY0ODkwZjUxOGUzNmI4OGY1MTljYTgwNDc1ODQwMjc3YTM0YjZlOGExMzVjYjZjYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xuZUfk-woff-AjTroeCnZe4PpIWbQQ2WVhFPQ5DprIw">

What OS? What's your folder structure?

**Comment by jrossi** [comment]
Mac OSX  15.1 (24B83)
Obsidian: Version 1.7.7 (Installer 1.5.3)

<img width="760" alt="Screenshot 2024-12-02 at 5 13 01 AM" src="https://github.com/user-attachments/assets/efae02be-bb1a-4abb-955d-1dabee00b7d4">

I changed it to a top level folder as I thought my Johnney.decimal folder setup my be an issue.  Before trying this out. it was set to:  `00-09 System/01 Inbox/01.03 Copilot chat logs`

**Comment by ticmain** [comment]
Yes. On Android.

**Comment by upnix** [comment]
This is the same as the bug here, I believe:
https://github.com/logancyang/obsidian-copilot/issues/628

**Comment by StefanLindow** [comment]
I have this issue on Windows. 
windows 10 enterprise
Obsidian 1.8.7

> plugin:copilot:174732 Error saving chat as note: Folder already exists.
> eval @ plugin:copilot:174732
> DevTools failed to load source map: Could not load content for app://obsidian.md/styles.css.map: System error: net::ERR_FILE_NOT_FOUND


and on clickin on it, i get a red cross here: 
>  console.error("Error saving chat as note:", err2String(error));

**Comment by logancyang** [comment]
If this is still an issue please reopen
